- README.md
- src/components/Alert.jsx
- src/components/Avatar.jsx
- src/components/FormField.jsx
- src/components/Menu.jsx
- src/components/MenuItem.jsx
- src/components/RepositoryCard.jsx
- src/components/Sidebar.jsx
- src/components/Switch.jsx
- src/components/Tag.jsx
- src/components/TextInput.jsx
- src/components/Token.jsx
- src/components/UserCard.jsx
- src/components/icons/createIcon.js
- src/index.js
- src/setupTests.js
propTypes and defaultProps are about to get deprecated. Most IntelliSense implementations for JSX won't rely on them, but on function args in the future.
Also adds a missing export and edit README
> Remove default props, add more exports

- src/components/Sidebar.stories.tsx
- src/components/Sidebar.tsx
To match the active item based on a regex.
Useful for determining the 'Explore' active state based on multiple URLs: '/explore', /explore/foo'
> Add matchedUrl param on SidebarItem

- src/components/Sidebar.tsx
So it transitions opacity when collapsed
> Fix Sidebar item opacity

- package-lock.json
- package.json
- src/components/Alert.tsx
- src/components/Avatar.tsx
- src/components/Divider.tsx
- src/components/FormField.tsx
- src/components/Input.tsx
- src/components/InstalledLabel.tsx
- src/components/RepositoryCard.tsx
- src/components/Select.tsx
- src/components/Sidebar.tsx
- src/components/Switch.tsx
- src/components/Tag.tsx
- src/components/Token.tsx
- src/components/UserCard.tsx
- src/components/icons/createIcon.tsx
To pass references from a parent component.
It's a best practice that was on my to-do list for a long time.
It also enables us to use a tooltip (honorable or other) around our components. 
Many UI libs such as MUI, Chakra or Honorable require refs to be passed to use the Tooltip component.
> Use forwardRef in every component

- src/theme.tsx
The current behavior on `padding={0}` or `margin={0}` is incorrect (noop). This fixes it (actual spacing value).
> Allow 0 as a spacing value

- package-lock.json
- package.json
https://www.npmjs.com/package/pluralsh-design-system contains v1.113.0, this bumps version in the package.json to avoid errors like https://github.com/pluralsh/design-system/runs/7234261241?check_suite_focus=true.
> Bump version to fix CI

- src/theme.tsx
FYI, Honorable allows you to do:
```jsx
<Div
backgroundColor-desktop-up="white" // Over desktop screens
backgroundColor-desktop-down="blue" // Below desktop screens
backgroundColor-desktop-exact="red" // Only desktop screens
display="block"
display-desktop="flex" // Same a display-desktop-exact
width-some-other-breakpoint="100%" // someOtherBreakpoint is a custom breakpoint
/>
```
This PR sets two breakpoints:
- desktop
- desktop-large
> Add breakpoints to theme

- src/components/RepositoryCard.tsx
Using absolute `@src/` imports causes errors when using the library in the plural app. We should only use relative paths until/unless we figure out a way to have absolute paths resolve properly on build.
> Don’t use absolute imports

- src/index.ts
This reverts my last change. As discussed on Slack this component should not be used anymore.
> Unexport tag component

- package.json
- src/components/Tooltip.tsx
- yarn.lock
Fixes error `Module not found: Error: Can't resolve 'react-merge-refs’` when used externally
> Fix missing dependency

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- package.json
CD is no longer able to push changes after version bump and publish because of new branch protection rules. This makes master out of sync. First publish job fails after publishing new version but before commit, all next ones fail during publish as versions are out of sync and it fails to override already published version.
If you have any ideas how to make it better let me know. This tries to move away from commits in CD as this can bring some security risks. Now when we would need to add access token to make it work then it would be unsafe.
```
Local version from package.json is 1.143.0
Published version from npm registry is 1.145.0
This version is already published, update local version to be bigger than published one
```
> Require version updates in pull requests

- src/components/Card.tsx
- src/components/Chip.tsx
- src/components/Token.tsx
- src/stories/Chip.stories.tsx
- src/stories/Token.stories.tsx
- src/theme.tsx
- Used `flex` instead of `p` and element that embeds children (it was throwing errors that `p` cannot have children`
- Updated `Token` component as in the design it does not have border. [Ref](https://www.figma.com/file/kZ69OGXTQe3Gu0wzGdDyoO/Marketplace-Tab?node-id=910%3A34710).
- Added `hue` property to the `Token` component
> Update chip component

- package.json
- src/components/Divider.tsx
Ref: https://www.figma.com/file/rCCFdkFyrfdcr7nCwetYOk/Onboarding-Experience?node-id=1225%3A36239
Here it uses `text-xlight` instead of `text-light`.
> Allow to override divider color

- .storybook/preview-head.html
- package.json
- src/components/Code.tsx
- src/stories/Code.stories.tsx
It's related to [DES-139](https://linear.app/pluralsh/issue/DES-139/code-blocks). Once it will be merged we'll need to bump version in plural app and update theme in it as well.
> Update code block styling

- package.json
- src/index.ts
It's needed for packages view.
> Export sub tab component

- package.json
- src/components/ListBox.tsx
- src/components/SubTab.tsx
- src/components/Tab.tsx
- src/components/TabList.tsx
- src/index.ts
- src/stories/TabList.stories.tsx
After actually trying to use the `TabList` in the app, I realized it was too complicated. This should simplify things and bring usage more inline with the `Select` and `ComboBox` components. Also fix some issues with focus styles.
See the "Tab List" story for new usage examples. I'm happy to go through the app and update any existing Tab Lists if approved.
> Tab List improvements

- package.json
- src/components/Code.tsx
- src/stories/Code.stories.tsx
Only the interior of the code component can be scrolled. Header and copy button positions are fixed now. See the new stories.
Closes ENG-515.
> Improve code block scrolling

- package.json
- src/components/ListBox.tsx
Stops the following react warning when using ListBox, TabList, Select or ComboBox:
> Warning: React does not recognize the `textValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> Prevent react warning

- package.json
- src/components/Chip.tsx
- src/stories/Chip.stories.tsx
We don't need height limits as proper line heights and paddings allow to keep the sizes right. It's required to close [ENG-525](https://linear.app/pluralsh/issue/ENG-525/[vqa]-vulnerabilities).
> Remove max height restrictions from chips

- package.json
- src/components/Chip.tsx
- src/stories/Chip.stories.tsx
I have missed this in my previous change. It's needed so chip will not stretch to 100% when text wraps.
> Set chip width to min-content

- package.json
- src/components/TabList.tsx
- src/stories/TabList.stories.tsx
Needed for instances where adding an extra <div> to the DOM for the Tab Panel will break the layout.
> Allow arbitary components to be used as TabPanel

- package.json
- src/components/TabList.tsx
Using the ‘as’ property was breaking in certain circumstances. This should fix that. Needed for [ENG-534 - Set proper scrollable areas](https://linear.app/pluralsh/issue/ENG-534/set-proper-scrollable-areas)
> Fix TabPanel ‘as’ functionality

- package.json
- src/components/IconFrame.tsx
- src/stories/IconFrame.stories.tsx
- src/stories/PageCard.stories.tsx
This allows the dynamic setting of the initials in a blue `IconFrame`. If `initials` is specified, that string is used directly. Otherwise if `name` is provided, that will be automatically converted to initials. Needed for use in certain `PageCards`
> Allow dynamic setting of initials in IconFrame

- package.json
- src/components/Card.tsx
- src/components/ContentCard.tsx
- src/stories/ContentCard.stories.tsx
Bottom padding was getting ignored for `ContentCards` with scrolling content due to flexbox weirdness. This fixes that as well as creates appropriate scrollbar coloring for all `Card` hues.
> Fix Layout/Styling issues on ContentCards

- package.json
The other day I forgot to run `npm run build` before publishing the package, resulted in an empty project.
This ensures that the build script is ran before publishing.
> Add prepublishOnly build script

- package.json
- src/components/AppIcon.tsx
- src/components/PageCard.tsx
- src/index.ts
- src/stories/AppIcon.stories.tsx
- src/stories/ComboBox.stories.tsx
- src/stories/Icons.stories.tsx
- src/stories/ListBox.stories.tsx
- src/stories/Select.stories.tsx
Currently the component known as 'App Icon' in the figma design system is implemented as `<IconFrame>`, which is a name needed for different component that hasn't been implemented yet. There seems to be only one instance of this component in the app right now, so I think it's best to fix this now rather than live with less descriptive component names for the rest of time. This may potentially disrupt some in-progress work if you're using the `<IconFrame>` component. But should be an easy swap when you update the design system. I'll delay implementing the new 'Icon Frame' until the transition is complete.
> Fix name of App Icon

- package.json
- src/components/Code.tsx
- src/hljs.ts
To reduce the bundle size in the app, we now explictly import and register only the languages we want for highlight.js. I picked languages that seemed popular and/or didn’t increase the bundle size too much. LMK if you think we should add or remove any languages. 
Results of `yarn analyze` after building the plural app below:
> Reduce highlight.js bundle size

- package.json
- src/components/ContentCard.tsx
- src/components/ListBox.tsx
Importing from ‘/index’ was breaking when using the design system in NextJS. This fixes that.
> Fix imports that break in NextJS

- package.json
- src/components/Stepper.tsx
- src/components/Tooltip.tsx
- src/stories/Stepper.stories.tsx
Added new feature to hide titles in vertical `Stepper` components. First, the text is allowed to wrap when the width is too small.
Second, I aded two new props
- `collapseAtWidth`: If set, when the component width drops below this value, then the step titles will be replaced by tooltips when hovering the circles
- `forceCollapse`: If set, the titles will be replaced by tooltips regardless of width
These are available to adjust in storybook and there's also `containerWith` and `showContainer` props there to help see the transitions. https://pluralsh-design--pr218-klink-stepper-improv-msq3p6z3.web.app/?path=/story/stepper--vertical
> Improve Stepper component

- package.json
- src/components/Code.tsx
`Code` component wasn't forwarding the ref, despite using forwardRef(). This fixes the warning:
`Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?`
> Fix forwardRef warning on Code component

- package.json
- src/components/RepositoryChip.tsx
The top one has the hover state:
> Add hover state to RepositoryChip

- package.json
- src/components/Code.tsx
- src/components/Highlight.tsx
- src/stories/Button.stories.tsx
- src/stories/Code.stories.tsx
Update styling of `Code` component
[Figma](https://www.figma.com/file/9nkKaihJkJzFIgoBADk0yQ/Docs?node-id=1%3A64&viewport=-15071%2C-35%2C0.71)
[Linear](https://linear.app/pluralsh/issue/ENG-688/update-code-block-component)
Tabs functionality has been pushed back into a [new ticket](https://linear.app/pluralsh/issue/ENG-862/add-tabs-functionality-to-code-component) so as not to block Docs launch.
> ENG-688 update code block component

- package.json
- src/theme/colors.ts
Since the big app front-end refactor is still in progress, I’m restoring the ‘error’ colors until it’s safe to replace them all with ‘danger’ colors in the app.
> Restore ‘error’ colors

- package.json
- renovate.json
have renovate bump the version with it's built-in mechanism rather than using `yarn version minor` command.
> Renovate built in version bump

- package.json
- renovate.json
Enables auto-merging in renovate for patch versions, and up to minor versions for dev dependencies.
> enable auto-merging in renovate

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- package.json
The Node version specified in our CI was getting diverged since there was no single source of truth. This PR specifies the node version in the `package.json` and our CI will read it from there and install the appropriate version. This will also be useful for keeping our CI up to date with our package as Renovate might update the node version.
> feat: specify engine in package.json + use in ci

- package.json
- yarn.lock
This PR removes react-scripts from our package.json, since I believe this isn't needed anymore after the switch to vite and it brings in a lot of (vulnerable) dependencies.
> fix: remove react-script

- src/components/IconFrame.tsx
- src/components/ProgressBar.tsx
- src/stories/IconFrame.stories.tsx
Update icon frame according to design: https://www.figma.com/file/i3IQooR2YCCXiCJNL98lWr/%F0%9F%8E%A8-Official-Design-System?node-id=3236%3A13864&t=6Rm8Psztsk1w5gi1-4
Allow changing progress bar colors.
Both changes are required for https://github.com/pluralsh/console/pull/125.
> feat: Update icon frame and allow customizing progress bar colors

- src/stories/Modal.stories.tsx
Adds the ability for a modal to be pinned to the top.
Here is how it is done: 
The props discovery is available with typescript:
> feat: Add pinned to top Modal story

- package.json
- src/components/Table.tsx
- yarn.lock
Scrolling is now much smoother, and doesn’t hop around after finished scrolling. To come later: stable column widths when scrolling.
> fix: Scrolling in virtualized tables is jumpy

- src/components/Table.tsx
- src/types/react-table.d.ts
A long line with a public key overlapped when truncated and `width` was not set.
Truncated fields with template grid size set were not aligned to the center.
> fix: Small table styling update

- src/components/ValidatedInput.tsx
- src/stories/ValidatedInput.stories.tsx
It's a proposed solution to keep `ValidatedInput` component and align its design with current version of `FormField` component.
---
- https://app.asana.com/0/0/1203811012695682
> fix: Display `ValidatedInput` errors below input field

- package.json
- src/components/pricingcalculator/PricingCalculator.tsx
- src/components/pricingcalculator/PricingCalculatorExtended.tsx
- src/components/pricingcalculator/misc.tsx
- yarn.lock
Relying on container size is safer/more flexible option than using media queries.
Unfortunately styled-components do not support it and I had to use additional library. See: https://github.com/styled-components/styled-components/issues/416.
> fix: Use container query to properly size pricing calculator

- src/components/pricingcalculator/PricingCalculator.tsx
- src/components/pricingcalculator/PricingCalculatorExtended.tsx
- src/stories/PricingCalculator.stories.tsx
- src/stories/PricingCalculatorExtended.stories.tsx
- Allow setting default values
- Display 0-5 as selected option instead of 0
- Use singular "cluster" form when 1 cluster is selected
> fix: Pricing calculator improvements

- src/components/Codeline.tsx
- src/stories/Codeline.stories.tsx
Required by the CLI UI since it does not support `window.navigator.clipboard` and requires some custom logic to handle clipboard copy.
> feat: Allow usage of custom onCopy method for codeline

- src/components/Breadcrumbs.tsx
- src/components/Input.tsx
- src/components/Select.tsx
- src/components/Table.tsx
- src/stories/Input.stories.tsx
- src/theme.tsx
- src/theme/resets.ts
- Add `<Input>` `titleContent` variant for use on Marketplace page
- Fix focus styling on `<Input>` that have `prefix`, `suffix` or `titleContent`
- Make `<Breadcrumbs>` more accessible
- Fix react `key` warning in `<Table>`
> feat: Multicluster components

- src/components/Breadcrumbs.tsx
Prevent selectTrigger’s `isOpen` prop from being passed to underlying html element
> fix: Prevent react warning with `<Breadcrumbs>`

- package.json
- src/components/SubTab.tsx
- src/components/wizard/Installer.tsx
- src/types.ts
- yarn.lock
`styled-componets` v6 was breaking `grommet` so going back to v5 :(
> feat: Revert `styled-components` to v5

- src/theme/focus.ts
- src/theme/text.ts
Honorable will replace portions of css variable names with the actual color value if any portion matches a known color name. This works around that by setting the color to an intermediate variable first.
> fix: Some colors in honorable components are incorrect

- src/theme/focus.ts
- src/theme/text.ts
styled-components will auto-convert to kebab-case when declaring a var, but not when referencing the var, so css vars were getting out of sync. Changed all css vars to kebab-case to avoid this.
> fix: CSS variables out of sync in styled-components

- src/stories/A.stories.tsx
- src/theme/marketingText.ts
- src/theme/text.ts
Visited links weren't getting their colors applied due to security restrictions against setting css variables in `:visited` pseudo-classes. This sets the intermediate variables needed to avoid mangling by Honorable outside the pseudo classes, so we can set the `color` property directly in the pseudo-classes (which is one of the few properties allowed to be set within `:visited`).
Also added `:hover` styles for marketing inlineLinks. Intermediate css variables aren't needed there since we don't use marketing text styles with Honorable.
> fix: Styles not applied for :visited and :active inline links

- src/components/PopoverListBox.tsx
Accidentally included a change in the Datepicker PR that was causing dropdowns to be sized incorrectly. This reverts that change.
> fix: Broken dropdowns

- src/components/Card.tsx
- src/components/Chip.tsx
- src/stories/Chip.stories.tsx
Adds ability for clickable `Card` and `Chip` components to be tab-focusable and with proper focus styles.
> feat: Focus handling for Cards and Chips

- .storybook/main.ts
- package.json
- src/components/Accordion.tsx
- src/components/AnimatedDiv.tsx
- src/components/Layer.tsx
- src/components/LightDarkSwitch.tsx
- src/components/PopoverCornerScale.tsx
- src/components/PopoverListBox.tsx
- src/components/Switch.tsx
- src/components/TreeNavigation.tsx
- src/index.ts
- src/stories/Table.stories.tsx
- src/types/styled.d.ts
- tsconfig.json
- vite.config.ts
- yarn.lock
- Switch component hover style fixed
- Switch component can now be styled via styled-components
- Enabled use of styled-components `css` prop, which should help with the incremental migration away from honorable.
> feat: Improve Switch styling and enable `css` prop

- src/components/Stepper.tsx
- src/components/StepperStep.tsx
- src/components/StepperStepConnection.tsx
`css` prop isn’t supported for imported components, so converted to styled-components for use in our apps
> fix: Broken styles on Stepper when importing

- src/components/Button.tsx
- src/components/Input.tsx
- src/components/Modal.tsx
- src/stories/Input.stories.tsx
- src/stories/Modal.stories.tsx
- src/theme.tsx
- Remove excessive padding on Modals (this also fixes issue with scrolling content appearing below action buttons) 
- Allow Modals to be rendered as forms using `asForm` and `formProps` so actions can trigger form submission 
- Default Buttons to `type="button"` to prevent accidentally submitting forms on click.
- Fix wonky margins/padding on Inputs
> feat: Modal and Input improvements

- src/components/HonorableModal.tsx
Now properly closes when pressing Escape key.
> fix: Modal closing when pressing any character in the string “Escape”

- src/components/Chip.tsx
- src/components/ListBox.tsx
- src/components/SelectItem.tsx
- src/components/Table.tsx
- src/components/Toast.tsx
- src/components/pricingcalculator/controls/Control.tsx
- src/components/pricingcalculator/controls/ProvidersControl.tsx
- src/index.ts
- src/stories/Chip.stories.tsx
- src/stories/ComboBox.stories.tsx
- src/stories/ListBox.stories.tsx
- src/stories/Select.stories.tsx
- src/stories/Table.stories.tsx
- src/stories/Toast.stories.tsx
- src/utils/ts-utils.ts
- Fix crash with Pricing Calculator
- Add `danger` severity option for `Chips` and `Toasts` to bring severities into alignment across design system
- Automatically set `textValue` for `ListBoxItem`s when possible to reduce `react-aria` warnings
- Fix issue where `Table` was requiring unneeded props for `reactVirtualOptions`
- `Table` - Add ability to listen to changes in virtual rows with `onVirtualSliceChange`
> fix: Pricing Calculator crash + Typescript fixes

- src/components/IconFrame.tsx
Fixes issue where `IconFrame`s using the `as` prop would have incorrect styling.
Before:
After:
> fix: Incorrect styling of `IconFrame` when using `as` prop

- src/components/ComboBox.tsx
- src/components/TextSwitch.tsx
- src/stories/ClusterTagsTemplate.tsx
- src/stories/TextSwitch.stories.tsx
Add new `TextSwitch` to be used inside `ComboBox` for configuration search filtering.
> feat: Add `TextSwitch` component

- src/components/Modal.tsx
- src/stories/Modal.stories.tsx
Icon in `Input` element showing above actions background
Icon is now properly blocked by actions background
> fix: Parts of elements appear above the Modal actions area when scrolling

- src/components/ComboBox.tsx
- src/components/TagMultiSelect.tsx
- src/index.ts
- src/stories/ComboBox.stories.tsx
- src/stories/TagMultiselectTemplate.tsx
I left the filtering for the parent component because the logic in cluster is too specific and it requires refetches with different arguments.
> feat: create component for tag multi select with new design

- src/components/ComboBox.tsx
- src/components/TagMultiSelect.tsx
- src/index.ts
- src/stories/ComboBox.stories.tsx
- src/stories/TagMultiselectTemplate.tsx
- add callback to run when the match type changes
- remove arrow from input
- change how component is exported
> fix: Fix tag multi select

- package.json
- src/components/Table.tsx
added an optional flag to remove the header from a table
also fixed an inconsistency with the pre-commit hook not lining up with what the actual PR linter checks for. Might want to look into this further at some point but not urgent
> feat: added hide header option to tables

- src/components/ArrowScroll.tsx
- src/components/TabList.tsx
- src/index.ts
wraps around a component with horizontal scroll and replaces its scroll bar with this effect:
https://github.com/pluralsh/design-system/assets/28611154/e1681142-0907-4ede-8840-866e266f8beb
started by just putting it in TabList components that have scroll enabled, though we'll probably find some other spots where it might be good to use
> feat: added arrow scroll component

- src/components/ArrowScroll.tsx
was overriding its child refs, which at the very least was causing accessibility to break for keyboard users on tabs. likely would cause other issues too
> fix: fix ref issue on arrow scroll

- src/components/ArrowScroll.tsx
needed to watch for the element it's wrapping around to resize rather than the window itself. was causing issues when the number of tabs on a page changed, for example (function wasn't firing to see if it should show/hide the arrows)
> fix: bug in arrowscroll causing it to sometimes show/hide at the wrong times

- src/components/Table.tsx
gives the option for base, raised, or stripes (current default). been running into a number of cases where we want the row colors on a table to all be the same
also small semantic change, using "lighter" for the row color was confusing because it's only true in one of light/dark mode. "raised" makes more sense
> feat: add prop to set table row background color

- src/components/ArrowScroll.tsx
when the arrow scroller was hidden it was still blocking components under it from being clicked on
> fix: pointer events under arrow scroll

- src/components/ComboBox.tsx
- src/components/Flyover.tsx
- src/components/ListBoxItemChipList.tsx
- src/components/TagMultiSelect.tsx
also some general cleanup
adds option to put chip list below the input instead of inside
also adds a "reset tags" button
> feat: add new options to TagMultiSelect

- src/components/Table.tsx
was trying to pull an id from a null value any time a loader row was rendered (this is what was happening in the users table because the default page size there is 20)
> fix: table error

- src/components/Modal.tsx
- src/components/Table.tsx
makes modals have a consistent fill level, and also makes table row hover state go away when inner buttons are hovered
> fix: table highlighting and modal fill level

- src/components/Breadcrumbs.tsx
- src/components/Modal.tsx
- src/components/SidebarItem.tsx
- src/components/Tooltip.tsx
these weren't actually affecting things functionally, but the console was getting polluted with small errors
> fix: various react errors in console

- package.json
- src/components/Markdown.tsx
- src/stories/Markdown.stories.tsx
- yarn.lock
adds https://github.com/remarkjs/remark-gfm to our markdown component, adding the ability to parse plain links among other things
> feat: add remark gfm plugin

- src/components/Flyover.tsx
> fix: modal using flyover animations

- src/components/ComboBox.tsx
- src/components/TreeNavigation.tsx
quick fix for links not being passed correctly to treenav components
also removed an unused prop causing a console warning
> fix: treenav issue

- src/components/Layer.tsx
position wasn't being set correctly
> fix: broken toast

- src/components/Select.tsx
- src/components/TabList.tsx
- src/components/TagMultiSelect.tsx
reverts a couple changes from https://github.com/pluralsh/design-system/pull/650/ in cases where styled component props actually do need to propagate to children
also unrelated fix for TagMultiSelect arrows not flipping up and down when the select opens
> fix: revert incorrect transient props

- src/components/table/FillerRows.tsx
- src/components/table/SortIndicator.tsx
- src/components/table/T.tsx
- src/components/table/Table.tsx
- src/components/table/Tbody.tsx
- src/components/table/Td.tsx
- src/components/table/Th.tsx
- src/components/table/Thead.tsx
- src/components/table/Tr.tsx
- src/components/table/colors.ts
- src/components/table/hooks.ts
- src/index.ts
- src/markdoc/nodes/table.markdoc.ts
- src/stories/Table.stories.tsx
> feat: Table fill level

- src/markdoc/components/Callout.tsx
something with the old syntax was causing a bug when bundled, probably related to the function within a function
> fix: callout causing bug in prod

- src/components/contexts/FillLevelContext.tsx
- src/components/table/FillerRows.tsx
- src/components/table/Table.tsx
- src/components/table/Td.tsx
- src/components/table/Th.tsx
- src/components/table/Tr.tsx
- src/components/table/colors.ts
- src/components/table/hooks.ts
- src/components/table/tableUtils.ts
- src/index.ts
gives a more distinguished background color to expander rows and adds a top border to them
plus adds an escape hatch in case we need more flexibility
also fixes some bugs related to virtualization which were causing virtualized tables to be pretty glitchy with expander rows, even more so if the columns were sorted
(main fix was ensuring the virtualizer includes the expanded content when measuring an open row's height, as well as ensuring data-index tracks the virtual row index as opposed to the original table index)
> feat: improve table expander

- src/components/SegmentedInput.tsx
- src/hooks/useIsFocused.tsx
- src/index.ts
- src/stories/SegmentedInput.stories.tsx
useful for date/time inputs among other things
index.ts changes are from linting
part of PROD-3243
> feat: add SegmentedInput component

- package.json
- src/components/Code.tsx
- src/components/Highlight.tsx
- yarn.lock
mostly stems from quirks with highlight.js (https://github.com/highlightjs/highlight.js/issues/1677)
setting the highlight component key to the code string will force react to rebuild the component if the content changes, which seems to be the cleanest/safest way to handle this
ultimately we should probably just remove highlight.js and replace it with monaco-editor here, which is already being used by our CodeEditor component. it's much more modern and react-friendly, plus it's smarter with how it handles language loading so they're not all included in the bundle by default
also fixes some deprecation warnings highlight.js was throwing
> fix: code blocks lose highlighting if content changes

- .github/workflows/ci.yml
- src/components/CodeEditor.tsx
- src/components/Select.tsx
- src/stories/Select.stories.tsx
- add "Remeasure Fonts" action with Ctrl/Cmd+B shortcut to allow quickly fixing annoying issue when cursor position is off
- add better styling to `Select` when `isDisabled` is set to true
> feat: add "Remeasure Fonts" action to CodeEditor and update Select disabled state styling

- src/hljs.ts
adds diff syntax highlighting to our highlight component, needed to visualize patches. part of PROD-3731
> feat: add diff highlighting

- src/components/table/Td.tsx
the only place we use this currently is the flow preview templates table, but it fixes a layout bug there
> fix: hide overflow on custom expander rows

- src/components/Markdown.tsx
- src/stories/Markdown.stories.tsx
adds styling for tables in our markdown component, particularly useful inside the chatbot
> feat: add table support to markdown

- package.json
- src/components/Flex.tsx
- src/components/Markdown.tsx
- yarn.lock
the way we were parsing the language for a codeblock seemed to be based off an older version of react-markdown, this fixes that
also refactors the component a bit to clean up and make more TS-friendly
> fix: markdown syntax highlighting bug
