- src/components/Avatar.jsx
- src/components/Avatar.stories.jsx
That displays the initials of the user.
> Add Avatar

- package-lock.json
- package.json
- src/components/Sidebar.jsx
Merging now because I need it ASAP
> Fix sidebar

- src/GrommetDecorator.jsx
- src/components/Sidebar.jsx
> Add link wrapper to Sidebar

- .eslintrc.json
- src/components/InstalledLabel.stories.jsx
- src/components/InstalledLabel.tsx
- src/components/RepositoryCard.jsx
- src/components/icons/createIcon.js
> Add InstalledLabel

- .eslintrc.js
- src/components/Sidebar.stories.tsx
- src/components/Sidebar.tsx
> Fixes 1  - Sidebar

- src/components/Sidebar.stories.tsx
- src/components/Sidebar.tsx
Change some of the id lookup and collapse behavior of the sidebar.
Major changes:
- The way the sidebar handles its active item internally.
- When you collapse the sidebar on some sub-item selected, the top-level parent item gets some active styling.
> Enhance Sidebar

- src/components/Sidebar.tsx
> Fix sidebar collapse behavior

- src/components/Divider.stories.tsx
- src/components/Divider.tsx
> Add Divider

- package-lock.json
- package.json
- src/components/Alert.tsx
- src/components/FormField.tsx
- src/components/RepositoryCard.tsx
- src/components/Sidebar.tsx
- src/components/UserCard.tsx
- src/theme.tsx
Change default font size to 14px.
Update deps.
> Edit html font size

- src/components/FormField.tsx
- src/components/RepositoryCard.tsx
- src/components/Select.stories.tsx
- src/components/Sidebar.tsx
With various updates from the meeting
> Design RepositoryCard

- package-lock.json
- package.json
- src/components/Alert.tsx
- src/components/Avatar.tsx
- src/components/CheckBox.stories.tsx
- src/components/Divider.tsx
- src/components/DropdownButton.stories.tsx
- src/components/InstalledLabel.tsx
- src/components/RepositoryCard.tsx
- src/components/Sidebar.stories.tsx
- src/components/Sidebar.tsx
- src/components/Tag.tsx
- src/components/Token.tsx
- src/components/UserCard.tsx
- src/theme.tsx
And use Flex component where needed.
> Add dropdown button

- package-lock.json
- package.json
- src/components/CheckBox.stories.tsx
- src/components/Switch.stories.tsx
- src/theme.tsx
> Fix ts-ignores

- src/components/Tooltip.stories.tsx
- src/theme.tsx
Useful in routes such as Artifacts.
Give it a theme color.
> Design Tooltip

- src/components/Input.tsx
Give it the base styles as well
> Improve Input

- package-lock.json
- package.json
- src/components/CheckBox.stories.tsx
- src/theme.tsx
> Fix Checkbox

- .storybook/preview-head.html
- src/stories/TypeScale.stories.tsx
- src/theme.tsx
https://pluralsh-design--pr57-klink-semantic-type-wlhlhn7e.web.app/?path=/story/type-scale--all
> Added semantic type scale

- src/theme.tsx
> Design Select component

- README.md
- package.json
- src/components/ValidatedInput.tsx
- src/index.ts
- src/stories/ValidatedInput.stories.tsx
Just simplifies reused logic around validating input fields we can use elsewhere
> Add validated input component

- src/theme.tsx
> Design Modal

- src/components/Chip.tsx
Updated component colors:
To mirror design:
> ENG-246 Update chip colors

- .gitignore
- src/components/RepositoryCard.tsx
- src/stories/RepositoryCard.stories.tsx
> ENG-251 Add private switch to repo card

- src/components/RepositoryCard.tsx
> ENG-252 Fix repo card

- src/theme.tsx
Moved the code from: https://github.com/pluralsh/plural/pull/319 here as per @dherault suggestion. It should make sure that this styling will be used globally and also support theming.
> ENG-279 - Update global scrollbar styling

- src/components/RepositoryCard.tsx
> Adjust repo card styling

- src/components/RepositoryCard.tsx
> Update repo card vertical spacings

- src/components/Tab.tsx
> Make Tab components forward refs

- package-lock.json
- package.json
- src/stories/ButtonGroup.stories.tsx
- src/theme.tsx
Add a story to display how to use honorable's ButtonRow in theme with the DS.
> Add ButtonRow story

- src/components/SubTab.tsx
- src/components/Tab.tsx
- src/components/TabList.tsx
- src/stories/Tab.stories.tsx
- src/stories/TabList.stories.tsx
[Linear](https://linear.app/pluralsh/issue/ENG-377/create-subtabs-components) / [Figma](https://www.figma.com/file/i3IQooR2YCCXiCJNL98lWr/%F0%9F%8E%A8-Official-Design-System?node-id=2242%3A11925)
> ENG-377 - Create Subtabs Component

- src/index.ts
Forgot to export the components for TabList, so fixing that here
> Export TabList components

- src/stories/_SemanticSystem.stories.tsx
- src/theme.tsx
[Linear ticket](https://linear.app/pluralsh/issue/ENG-392/update-overline-text-style)
overline text style changed to 12px font, 16px line height, and 1.25px letter spacing.
> ENG-392 - Update "overline" text style

- package.json
- src/components/Codeline.tsx
- src/components/Tooltip.tsx
- src/stories/Codeline.stories.tsx
- src/stories/Tooltip.stories.tsx
- yarn.lock
[Linear Ticket](https://linear.app/pluralsh/issue/ENG-404/update-codeline-component)
Also updated the Tooltip component to use with Codeline
> ENG-404 - Update Codeline Component

- package.json
- yarn.lock
Changed styled-components to a peer dependency to prevent it from being loaded twice in a project.
> Fix styled-components issue

- package.json
- src/components/LoopingLogo.tsx
- src/components/LoopingLogoWrapper.tsx
- src/components/icons/plural-animated/PluralLogomarkBottomLeft.tsx
- src/components/icons/plural-animated/PluralLogomarkBottomRight.tsx
- src/components/icons/plural-animated/PluralLogomarkDot.tsx
- src/components/icons/plural-animated/PluralLogomarkTopLeft.tsx
- src/components/icons/plural-animated/PluralLogomarkTopRight.tsx
- src/index.ts
- src/stories/LoopingLogo.stories.tsx
Ref: https://github.com/pluralsh/plural/blob/master/www/src/components/utils/AnimatedLogo.js
> ENG-491 - Add LoopingLogo component

- package.json
- src/components/Markdown.tsx
- src/stories/Markdown.stories.tsx
> Add main branch argument to markdown

- package.json
- src/components/FormField.tsx
- src/stories/FormField.stories.tsx
- src/stories/Input.stories.tsx
Add a new story to expose how multiline inputs work. No logic added.
> Expose multiline Input and FormField

- package.json
- src/components/Chip.tsx
It's needed as well for https://github.com/pluralsh/plural/pull/456.
> Set min-content height for chips

- package.json
- src/components/Chip.tsx
- src/stories/Chip.stories.tsx
Needed for https://github.com/pluralsh/plural/pull/456.
> Update chip component

- package.json
- src/components/EmptyState.tsx
- src/stories/EmptyState.stories.tsx
> Add EmptyState component

- package.json
- src/components/AppIcon.tsx
- src/stories/A.stories.tsx
- src/theme.tsx
[Linear](https://linear.app/pluralsh/issue/ENG-555/design-system-updates)
> ENG-555 - Design updates

- package.json
- src/components/Alert.tsx
- src/components/FormField.tsx
- src/components/FormTitle.tsx
- src/components/InstalledLabel.tsx
- src/components/UserCard.tsx
See https://www.figma.com/file/i3IQooR2YCCXiCJNL98lWr/%F0%9F%8E%A8-Official-Design-System?node-id=2232%3A13535.
`bold` applied font weight 700.
> Use font weight 600 instead of bold

- package.json
- src/components/ComboBox.tsx
- src/components/ListBoxItem.tsx
- src/components/PopoverListBox.tsx
- src/components/ReactAriaPopover.tsx
- src/components/Select.tsx
- src/stories/ListBox.stories.tsx
- src/stories/Select.stories.tsx
- Add a `destructive` (red label text) [ListBoxItem variant](https://pluralsh-design--pr188-klink-list-box-item-wehtsnfm.web.app/?path=/story/list-box--default)
- Make `<Select>` component dropdown width able to [fit to content](https://pluralsh-design--pr188-klink-list-box-item-wehtsnfm.web.app/?path=/story/select--default)
> Listbox / Select component improvements

- package.json
- src/components/Modal.tsx
- src/stories/Modal.stories.tsx
- src/theme.tsx
> Expose model size variants

- package.json
- src/components/RepositoryChip.tsx
- src/components/Stepper.tsx
Some small fixes to align to the Figma file better.
> Enhance onboarding components

- package.json
- src/theme.tsx
> Change text warning color to yellow[100]

- package.json
- src/components/StackCard.tsx
- src/stories/StackCard.stories.tsx
[Figma design](https://www.figma.com/file/HQRum7isI8qu0pcOLyCOMk/Plural-Stacks?node-id=159%3A32883).
Closes ENG-677.
> Add stack chip to stack card

- package.json
- src/components/RepositoryChip.tsx
- src/stories/RepositoryChip.stories.tsx
For the Stacks listing on the onboarding application selection.
> Edit repository chip to accept an icon

- package.json
- src/components/Button.tsx
Use Honorable props as previously it wasn't working in the app, only in Storybook.
> Refactor button pulse animation

- src/theme.tsx
Was blue on blue, is now white.
> Fix Button loading Spinner color

- package.json
- src/components/Code.tsx
- src/components/SubTab.tsx
- src/components/Tab.tsx
- src/components/TabList.tsx
- src/components/TabPanel.tsx
- src/index.ts
- src/stories/ButtonGroup.stories.tsx
- src/stories/Code.stories.tsx
- src/stories/InlineCode.stories.tsx
- src/stories/TabList.stories.tsx
- src/theme.tsx
- src/theme/focus.ts
- yarn.lock
This bundles a few related changes.
- [ENG-759](https://linear.app/pluralsh/issue/ENG-759/add-small-variant-to-button-group-component) - Add small variant to button group component
- [ENG-675](https://linear.app/pluralsh/issue/ENG-675/implement-modifications-to-tabs-component) - Implement modifications to tabs component
- [ENG-862](https://linear.app/pluralsh/issue/ENG-862/add-tabs-functionality-to-code-component) - Add tabs functionality to Code component
- No ticket for this but also updated all buttons to have their focus styles match the current [Figma file](https://www.figma.com/file/i3IQooR2YCCXiCJNL98lWr/%F0%9F%8E%A8-Official-Design-System?node-id=3236%3A14105).
> Tabs-related updates

- package.json
- src/components/Code.tsx
- src/components/TabPanel.tsx
- Fix issue with the initial selected tab for Code component.
- Remove logging statement
> Fix initial tabKey for Code component with tabs

- package.json
- src/components/Banner.tsx
- src/components/Callout.tsx
- src/components/icons/StatusOkIcon.tsx
- src/stories/Callout.stories.tsx
- src/types.ts
[ENG-913](https://linear.app/pluralsh/issue/ENG-913/banner-semantic-color-updates)
[ENG-915](https://linear.app/pluralsh/issue/ENG-915/callout-semantic-color-updates)
> ENG-913 + ENG-915 - Update colors/styles for Banner and Callout (

- package.json
- renovate.json
Signed-off-by: David van der Spek <vanderspek.david@gmail.com>
> have renovate bump the yarn version

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- README.md
- package.json
- renovate.json
- src/stories/Codeline.stories.tsx
- yarn.lock
This PR sets up Semantic Release for this repo and moves the package to the Pluralsh NPM organization.
> feat: move to npm org and use semantic release

- .storybook/main.ts
- package.json
- public/index.html
- yarn.lock
> fix: solve issue with storybook preview

- .storybook/main.ts
- index.html
- package.json
- public/index.html
- vite.config.ts
- yarn.lock
WIP: using this as hard to replicate locally.
> fix: fix vite production build

- .eslintrc.js
- src/components/AppIcon.tsx
- src/components/Card.tsx
- src/components/Checklist.tsx
- src/components/ChecklistFooter.tsx
- src/components/ChecklistItem.tsx
- src/components/Code.tsx
- src/components/ComboBox.tsx
- src/components/IconFrame.tsx
- src/components/ListBox.tsx
- src/components/ListBoxItem.tsx
- src/components/PageCard.tsx
- src/components/PopoverListBox.tsx
- src/components/ReactAriaPopover.tsx
- src/components/Tab.tsx
- src/components/TabList.tsx
- src/components/Tooltip.tsx
- src/index.ts
- src/stories/Card.stories.tsx
- tsconfig.json
Fixes errors when importing/exporting types in Storybook v7.
> fix: Errors with type imports and exports in Storybook

- package.json
- vite.config.ts
- yarn.lock
Fixed `yarn start` since it sometimes did not work due to conflicting plugins.
> fix(build): fix yarn start script

- src/components/Sidebar.tsx
- src/components/SidebarItem.tsx
- src/components/SidebarSection.tsx
- src/stories/Sidebar.stories.tsx
Ref: [Figma](https://www.figma.com/file/985LCDEqp4ckoMLOHSWkDF/Onboarding-v3?node-id=319%3A66929&t=HeOHqAXSR56D1ngs-4)
> feat: add vertical sidebar layout

- src/components/CodeEditor.tsx
Improvements of #379. Tested by linking it locally to console. Required for https://github.com/pluralsh/console/pull/125.
> fix: Code editor improvements

- src/components/Callout.tsx
- src/stories/Callout.stories.tsx
Ref: [Figma](https://www.figma.com/file/985LCDEqp4ckoMLOHSWkDF/Onboarding-v3?node-id=266%3A63076&t=VpsqOPT2kUzgsdLe-4)
> feat: Add expand/collapse option to the callout component

- src/theme/colors.ts
> fix: Edit text-input-disabled semantic token

- src/components/RepositoryChip.tsx
- src/stories/RepositoryChip.stories.tsx
---
- https://app.asana.com/0/0/1203837222695153
> fix: Update repository chip to not break on long app names

- src/components/Callout.tsx
---
- https://app.asana.com/0/0/1203845499454714
> feat: Make collapsed callout clickable eveywhere

- src/components/ListBoxItem.tsx
- Aligning with updated designs
---
- https://app.asana.com/0/0/1203845499454637
> feat: Add border to listbox/select/combobox footers

- src/components/Banner.tsx
- src/stories/Banner.stories.tsx
Improves the Banner component:
- Add new `fullWidth` prop
- Place border on the left
> feat: Improve Banner for Billing

- src/components/Banner.tsx
- src/stories/Banner.stories.tsx
Remove onClose button if no onClose action prop was given.
> feat: Improve banner

- src/components/SubTab.tsx
- src/stories/Tab.stories.tsx
---
- https://app.asana.com/0/0/1203845499454650
> fix: Fix sub tab hover

- src/components/Table.tsx
---
- https://app.asana.com/0/0/1203938060570365
> fix: Update table hover color

- src/components/Chip.tsx
The colors were the same, but updating in anyways in case it will change in the future.
Also changing fallback color for text to the correct one.
---
- https://app.asana.com/0/0/1203811003658355
> fix: Chip semantic color updates

- src/components/AppIcon.tsx
- src/components/AppList.tsx
- src/index.ts
- src/stories/AppList.stories.tsx
- src/theme/text.ts
New AppList component to simplify app management.
> feat: Add AppList component

- src/components/AppList.tsx
- src/components/ListBoxItem.tsx
- src/stories/AppList.stories.tsx
Allow disabling more menu actions if app is not alive.
> feat: Update AppList component

- src/components/Callout.tsx
- src/stories/Callout.stories.tsx
---
- https://app.asana.com/0/0/1204269978506948
> feat: Add dismissible callout variant

- src/components/RepositoryCard.tsx
- src/stories/RepositoryCard.stories.tsx
Will be useful for external contributions
> feat: Add release status chips

- src/components/Breadcrumbs.tsx
- src/components/Input.tsx
- src/components/Select.tsx
- src/stories/Input.stories.tsx
Fix margins and allow usage of `titleContent` and `startIcon` simultaneously
> fix: Fix <Input> styles

- src/components/Breadcrumbs.tsx
- src/components/TabPanel.tsx
- src/markdoc/components/Table.tsx
- src/markdoc/components/Tabs.tsx
- src/stories/Breadcrumbs.stories.tsx
- Make sure the `Breadcrumbs` component works without using `BreadcrumbsContext`
- Fix a few react warnings about unique `key`s
> fix: Breadcrumbs not working without BreadcrumbsContext

- src/components/Checkbox.tsx
- src/components/RepositoryCard.tsx
- src/stories/RepositoryCard.stories.tsx
- Add variant of `RepositoryCar` for marketing site
- Small change to `Checkbox` component that fixes mysterious overflow scrollbars when inside a collapsed accordion.
> feat: Marketing site variant for `RepositoryCard`

- package.json
- yarn.lock
> fix: Make `usehook-ts` dependency instead of dev dependency

- README.md
Update readme to hopefully trigger a new release
> feat: Trigger release

- .releaserc
- package.json
- yarn.lock
This should solve being able to create a major release by adding a `!` in the PR title.
> fix!: set commit analyzer preset

- src/components/Markdown.tsx
- src/stories/Markdown.stories.tsx
Fixes:
- Incorrect language detection in Markdown code blocks
- Broken relative links in Markdown
> fix: Markdown README issues

- src/components/Chip.tsx
- src/components/ComboBox.tsx
- src/components/Input.tsx
- src/components/Spinner.tsx
- src/stories/ComboBox.stories.tsx
- Fix ComboBox padding
- Remove honorable dependency for Spinner
- Make Chip slightly less honorable-dependent
> fix: Combobox padding

- src/components/EmptyState.tsx
- src/components/Table.tsx
- src/stories/Table.stories.tsx
- Show helpful message for empty tables  
- Change table selection interface to use react-table’s built-in functionality
> feat: Table improvements

- src/components/LoopingLogo.tsx
- src/index.ts
- Enable light mode for LoopingLogo
- Export light mode helper functions
> feat: Light mode support for LoopingLogo

- src/components/Select.tsx
- src/stories/Select.stories.tsx
---
- https://app.asana.com/0/0/1206497522790686
> fix: External elements shouldn't receive keypress events when Select is focused

- .husky/pre-commit
- package.json
- src/components/icons/BriefcaseIcon.tsx
- yarn.lock
- Fix issue when briefcase icon getting clipped when resized below 16px
- Upgrade `husky`
> fix: Briefcase icon is clipped when resized

- package.json
- src/components/CodeEditor.tsx
- src/stories/CodeEditor.stories.tsx
- tsconfig.json
- yarn.lock
`.storybook` dir files were reporting some minor errors so I have installed missing dep and update tsconfig
> fix: code editor resize and cursor alignment

- src/components/Flyover.tsx
> feat: move flyover close button to the right

- .vscode/settings.json
- package.json
- src/components/SidebarExpandButton.tsx
- src/components/SidebarItem.tsx
just needed to reduce the height back a bit so everything fits
also added different icon for when collapsed
> fix: spacing on sidebar

- src/components/Layer.tsx
also need to update this in the console
> feat: add ability for cookies banner to overlay everything else

- src/components/icons/ClipboardChecked.tsx
- src/icons.ts
> feat: add clipboard checked icon

- src/components/Flyover.tsx
- src/components/Table.tsx
a couple small changes needed to implement the updated upgrade plan designs
> feat: upgrade plan design improvement

- src/components/Accordion.tsx
- src/components/Flyover.tsx
- src/components/Table.tsx
meant to include this with https://github.com/pluralsh/design-system/pull/603
> feat: change accordion icon

- src/components/Select.tsx
- src/theme.tsx
a few stragglers were using the old 'normal' key instead of 'medium'
> fix: minor border radius issues

- src/components/Table.tsx
gives the ability to optionally remove table cells inner padding
> feat: add pad cells option to table

- package.json
- src/components/Accordion.tsx
- src/components/AccordionOLD.tsx
- src/index.ts
- src/stories/Accordion.stories.tsx
- src/theme.tsx
- yarn.lock
migrated our accordion to use Radix under the hood. much more robust and flexible (and accessible)
also adds support for horizontal orientation
> feat: new accordion component

- src/components/Accordion.tsx
- src/components/ComboBox.tsx
- src/components/IconFrame.tsx
- src/components/Select.tsx
- src/components/StepperStep.tsx
- src/components/Table.tsx
a couple of minor DS changes to support design QA on the console
> feat: various small tweaks

- src/components/Flex.tsx
- src/components/IconFrame.tsx
- src/theme/scrollBar.ts
small scrollbar color tweaks, looks a light nicer especially in light mode
also a couple small TS fixes
fixes PROD-2407, PROD-2417
> feat: update scrollbar

- src/components/IconFrame.tsx
- src/components/Modal.tsx
- src/components/ModalWrapper.tsx
meant to include these tweaks on #635
> fix: modal regressions

- src/components/ModalWrapper.tsx
makes the modal overlay optionally configurable
> feat: add overlayStyles prop to modal

- src/markdoc/nodes/table.markdoc.ts
incorporating fix from https://github.com/pluralsh/documentation/pull/308 into the DS
> fix: markdoc table node

- src/components/ArrowScroll.tsx
- src/components/Highlight.tsx
- src/components/ListBox.tsx
- src/components/TabPanel.tsx
- src/components/Tooltip.tsx
should fix most/all instances of this error (at least when it's caused directly by the DS):
> fix: some console errors with refs

- src/components/Flex.tsx
- src/components/table/Table.tsx
adds classname prop to Flex component so it can be the base for a styled component
adds back default table overscan
> fix: small tweaks

- package.json
- src/components/Callout.tsx
- src/components/Slider.tsx
- src/stories/Slider.stories.tsx
adds a "colorized" option to our slider for when we don't want the gradient progress bar style (part of PROD-3411)
also fixes some bugs causing warnings in the dev console
> feat: slider updates

- src/components/CodeEditor.tsx
It needs to be checked for undefined
> fix: code editor action

- src/components/icons/SmallAZIcon.tsx
last remaining cluster list icon
> feat: Add az icon
